### ISSUE TITLE
Områder som ikke har data vises likedan som alle andre

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#191]
### Screenshots
![image](https://user-images.githubusercontent.com/281359/37413272-f54b701e-27a6-11e8-9661-4163a30ea7df.png)

#### Expected
Bytt bakgrunnsfarge på listeelementer som ikke har data

**Comment by amundn** [comment]
![image](https://user-images.githubusercontent.com/13641108/37835571-c446b0da-2eb0-11e8-9c61-36018bb8cd10.png)
Hvilken farge vil du ha?

**Comment by bjornreppen** [comment]
Løst for lenge siden.
