### ISSUE TITLE
Kartlag blir hengende igjen etter å lukket meny og åpnet den igjen

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#192]
### Issue and Steps to Reproduce
- Velg en naturtype
- Lukk katalogen
- Åpne katalogen igjen
- Naturtypepolygonene henger igjen

### Screenshots
![state](https://user-images.githubusercontent.com/281359/37454732-9e7cabc8-283b-11e8-821e-f1bd57fe3ba2.gif)

#### Expected
Blankt kart igjen når man kommer på rot

**Comment by amundn** [comment]
Denne ser ut til å ha blitt rettet av en annen fix
