### ISSUE TITLE
Kalkinnhold - Skille mellom klassene i datasettet

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#200]
### Issue and Steps to Reproduce
Umulig å se forksjell på klassene i kalkkartet. Alle klasser ser like ut, uavhengig av hvilken klasse man hovrer over/velger farge på/klikker på.

https://grunnkart.firebaseapp.com/katalog/MI/KA 
navigerte:
rot
miljø
kalkinnhold
litt kalkrik

### Versions
20180316 kl. 13.00
### Screenshots
![image](https://user-images.githubusercontent.com/31729342/37519676-5993c2f0-291a-11e8-9a28-729e2c0d9112.png)

#### Expected
Å se forskjell på klassene

### Additional Details'
Ingrid E.M. har lyst til å se kalkkartet i testversjonen!

**Comment by amundn** [comment]
Denne er fikset tidligere:
![image](https://user-images.githubusercontent.com/13641108/38297491-ea38ef40-37f4-11e8-875e-ce4420190e94.png)
