### ISSUE TITLE
Miljøvariabelkart - ikke bare i punktinfo

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#202]
### Issue and Steps to Reproduce
Miljøvariabeldatasett (Miljø (LKM) og beskrivelsessytstemet) som i dag vises som punktinformasjon bør også kunne vises via navigering i treet. Dette gjelder:
BK-a (ultramfaisk bergrunn)
Biokjimatiske soner
Bioklimatiske seksjoner

### Versions
20180316_1500
### Screenshots
![image](https://user-images.githubusercontent.com/31729342/37524099-21ec8ecc-2929-11e8-838a-9463f215c296.png)
![image](https://user-images.githubusercontent.com/31729342/37524161-4748c00a-2929-11e8-8ca5-4dfabe942c9b.png)

#### Expected
se miljøvariabledatasettene i kartet

**Comment by runningbones** [comment]
Savner fortsatt muligheten til å vise  Bioklimatiske soner og  Bioklimatiske seksjoner som kartlag (ikke bare punktinfo)

**Comment by jarped** [comment]
Kan prioritere det denne uka. Vi har allerede en import (https://github.com/Artsdatabanken/grunnkart-dataflyt/blob/master/fme/in/02_nina.fmw.ignore), men vi må slå sammen cellene for å holde datamengden på et overkommelig nivå.

**Comment by runningbones** [comment]
I utganspunktet skeprisk til å slå sammen celler. Greit nok for å "vise" i innsyn, men mister reelt flyttall per celle og SSB ID?

**Comment by bjornreppen** [comment]
Lag raster tile set i PNG med verdier normalisert mellom 0-255 + en json som beskriver mappingen, noe ala:
```json
{
  range: {
    source: [-5.2,3.9],
    compressed: [0,255]
  }
}
```

**Comment by jarped** [comment]
PNG: http://it-webadbtest01.it.ntnu.no/data/png/seksjoner2017.png/seksjoner2017.png
JSON: http://it-webadbtest01.it.ntnu.no/data/png/seksjoner2017.png/seksjoner2017.json

**Comment by jarped** [comment]
http://it-webadbtest01.it.ntnu.no/data/mbtiles/

Ikke testet.

**Comment by jarped** [comment]
https://tiles.artsdatabanken.no/data/seksjoner2017/

https://tiles.artsdatabanken.no/data/soner2017/

**Comment by runningbones** [comment]
Kode | Sone/Seksjon | r | g | b | PCA2_min | PCA2_max | Pca1_min | Pca1_max
-- | -- | -- | -- | -- | -- | -- | -- | --
6SO-1 | lavalpin | 51 | 153 | 253 | 2,87 | 4,6657 |   |  
6SO-2 | nordboreal | 167 | 253 | 88 | 1,7402 | 2,8699 |   |  
6SO-3 | mellomboreal | 165 | 254 | 164 | 0,3802 | 1,74 |   |  
6SO-4 | sørboreal | 253 | 250 | 64 | -1,2999 | 0,38010000000 |   |  
6SO-5 | boreonemoral | 253 | 194 | 111 | -5,18580000000 | -1,30000000000 |   |  
6SE-1 | Sterkt oseanisk   seksjon (O3) | 50 | 67 | 253 |   |   | -5,88020000000 | -2,9401
6SE-2 | Klart oseanisk   seksjon (O2) | 104 | 117 | 252 |   |   | -2,93980000000 | -1,02000000000
6SE-3 | Svakt oseanisk   seksjon (O1) | 129 | 253 | 244 |   |   | -1,01990000000 | 0,60270000000
6SE-4 | Overgangsseksjon (OC) | 178 | 253 | 247 |   |   | 0,60310000000 | 2,34990000000
6SE-5 | Svakt kontinental   seksjon (C1) | 230 | 253 | 253 |   |   | 2,35000000000 | 4,31790000000

**Comment by runningbones** [comment]
https://github.com/Artsdatabanken/kverna/issues/196

**Comment by bjornreppen** [comment]
Min/max verdier for steg importert i https://github.com/Artsdatabanken/kverna/blob/master/kildedata/BS_6S.json
