### ISSUE TITLE
Informasjon om natursystemet vises ikke ved førstegangs lasting

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#204]
### Issue and Steps to Reproduce
Klikk på direkte [link til kartet](https://grunnkart.firebaseapp.com/punkt/10.468691702667453,60.34479050310029) viser ikke informasjon om naturområdet.

### Screenshots
![image](https://user-images.githubusercontent.com/281359/37553918-19dcc37a-29d1-11e8-84e9-f24dab2fb7ee.png)

#### Expected
Vis informasjonen også når url med /punkt lastes

**Comment by amundn** [comment]
Localid settes i state ved klikk i kartet og brukes for å hente ut naturområdeinfo, ved reload mister man localId og får dermed ingen naturinfo. Dette kan ihvertfall fikses om vi putter localId i url slik som lat/lon, men vet ikke om det er ønskelig
