### ISSUE TITLE
Placeholder mens data lastes

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#237]
### Issue and Steps to Reproduce
Erstatt data som ikke lenger er gyldig med animert placeholder mens nye data lastes

![image](https://user-images.githubusercontent.com/281359/37755582-584e2724-2da6-11e8-9fac-45d56851bbca.png)

**Comment by bjornreppen** [comment]
For eksempel https://github.com/buildo/react-placeholder

**Comment by runningbones** [comment]
avveneter. Ikke problem med dagens datamaengde.
