### ISSUE TITLE
Verneområder - legge inn i tre

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#245]
### Issue and Steps to Reproduce
Legge inn verneområder i base (og treet)

Hent fra: https://kartkatalog.miljodirektoratet.no/Dataset/Details/0 

Foreslår at vi bruker: http://trdefme02.miljodirektoratet.no/nedlasting/Naturbase/Shape/naturvern_utm33.zip

Etablerer rutiner for oppdatering (f.eks 1 dag hver måned)

**Comment by runningbones** [comment]
Ser ut som om verneområder har kommet inn i vectortilesettet, men mangler fortsatt som menypunkt (og i treet?)

**Comment by amundn** [comment]
for at det skal komme i treet må det inn i firebase. @bjornreppen ?

**Comment by bjornreppen** [comment]
[kverna/54](https://github.com/Artsdatabanken/kverna/issues/54)
