### ISSUE TITLE
IE gir en del warnings

### ISSUE THREAD

**Issue by amundn** [Artsdatabanken/ratatouille#257]
### Issue and Steps to Reproduce
Start i IE11, åpne konsollvindu og reload

### Versions
IE11

#### Actual
En del komponenter feiler med feilmelding i konsol, som resultat av dette ser ikke søket ut til å fungerel:

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check your code at TopBar.js:61.
    in TopBar (at VenstreVinduContainer.js:64)
    in div (at VenstreVinduContainer.js:55)
    in Route (at VenstreVinduContainer.js:53)
    in VenstreVinduContainer (at Grunnkart.js:209)
    in div (at Grunnkart.js:199)
    in div (at Grunnkart.js:168)
    in Grunnkart (created by Route)
    in Route (created by withRouter(Grunnkart))
    in withRouter(Grunnkart) (at App.js:32)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:31)
    in MuiThemeProvider (at App.js:30)
    in App (at index.js:6)
Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in div (created by AppBar)
    in div (created by Paper)
    in Paper (created by AppBar)
    in AppBar (at TopBar.js:38)
    in TopBar (at VenstreVinduContainer.js:64)
    in div (at VenstreVinduContainer.js:55)
    in Route (at VenstreVinduContainer.js:53)
    in VenstreVinduContainer (at Grunnkart.js:209)
    in div (at Grunnkart.js:199)
    in div (at Grunnkart.js:168)
    in Grunnkart (created by Route)
    in Route (created by withRouter(Grunnkart))
    in withRouter(Grunnkart) (at App.js:32)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:31)
    in MuiThemeProvider (at App.js:30)
    in App (at index.js:6)
react-map-gl: using mapbox-gl v0.44.1
There is no style added to the map.
kode:  mapstyle loaded: undefined
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check your code at TopBar.js:61.
    in TopBar (at VenstreVinduContainer.js:64)
    in div (at VenstreVinduContainer.js:55)
    in Route (at VenstreVinduContainer.js:53)
    in VenstreVinduContainer (at Grunnkart.js:209)
    in div (at Grunnkart.js:199)
    in div (at Grunnkart.js:168)
    in Grunnkart (created by Route)
    in Route (created by withRouter(Grunnkart))
    in withRouter(Grunnkart) (at App.js:32)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:31)
    in MuiThemeProvider (at App.js:30)
    in App (at index.js:6)
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check your code at TopBar.js:61.
    in TopBar (at VenstreVinduContainer.js:64)
    in div (at VenstreVinduContainer.js:55)
    in Route (at VenstreVinduContainer.js:53)
    in VenstreVinduContainer (at Grunnkart.js:209)
    in div (at Grunnkart.js:199)
    in div (at Grunnkart.js:168)
    in Grunnkart (created by Route)
    in Route (created by withRouter(Grunnkart))
    in withRouter(Grunnkart) (at App.js:32)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:31)
    in MuiThemeProvider (at App.js:30)
    in App (at index.js:6)

**Comment by bjornreppen** [comment]
Fixed

![image](https://user-images.githubusercontent.com/281359/49648643-d7249400-fa26-11e8-8ef7-30e82cb947c2.png)
