### ISSUE TITLE
Visning av objekter (naturområder) med en enkelt kode

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#258]
### Issue and Steps to Reproduce
I dag vises objekter (naturområder) med en enkelt kode som transparent med hvitt omriss. Tror vi med fordel kan beholde fargen også på dette nivået.

Krevende å se hva som er inkludert og eksludert i utvalget i kartfalta ved mange objekter

### Versions
20180404 12.45

### Screenshots
![image](https://user-images.githubusercontent.com/31729342/38303332-0c626586-3806-11e8-936c-4676f5d99666.png)

**Comment by bjornreppen** [comment]
Blir det ikke mest intuitivt hvis fargen beholdes?

### Eksempel
1. Står på NA => NA_T vises i grønt
2. Åpner NA_T => NA_T vises fortsatt i grønt 
   * NA_T1,2,3.. vises i 50 andre shades of grønt/mønster
