### ISSUE TITLE
Kreditering av opphav for bilder

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#262]
#### Expected

Ved klikk på et bilde, gjør en transisjon der bildet løftes ut og vises fullskjerm sammen med informasjon:
 * Navn (med lenke hvis finnes) 
 * lisens (med lenke til creativecommons el.)
 * lenker til lisens og opphav.

**Comment by amundn** [comment]
Er denne informasjonen lagret noe sted?

**Comment by bjornreppen** [comment]
Bruk denne som mock inntil vi har fått tanka det over i en egen base.  

```json
{
  "license": {
    "name": "CC BY-SA 3.0",
    "url": "https://creativecommons.org/licenses/by-sa/3.0/deed.en"
  },
  "attribution": {
    "name": "Wikipedia",
    "url": "https://no.wikipedia.org/wiki/Portal:Forside"
  }
}
```

**Comment by amundn** [comment]
Bruker den som mock nå, må ikke glemme å bytte ut mock'en etterhvert da.
![image](https://user-images.githubusercontent.com/13641108/39704647-4930d19e-520c-11e8-9b58-1c19777dd334.png)
