### ISSUE TITLE
Listekomponent med "drag to reorder" support for aktive kartlag

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#264]
![image](https://user-images.githubusercontent.com/281359/38485799-5b3c3046-3bdb-11e8-8e3c-913b41f8e958.png)

Funksjonaliteten for å vise liste av elementer + endre rekkefølge.  Noe i retningen av screenshot.  Innhold i listeelementene i en egen issue.

**Comment by amundn** [comment]
Relatert til https://github.com/Artsdatabanken/ratatouille/pull/275

**Comment by bjornreppen** [comment]
Ja! Prøv ut!

**Comment by runningbones** [comment]
ikke like aktuell med tranparency?
