### ISSUE TITLE
Bytt ut "Økologisk grunnkart" 

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#269]
endre til Ratatouille evt. andre forslag som kommer opp her.

**Comment by runningbones** [comment]
NiN-kart

**Comment by bjornreppen** [comment]
Kart = skjønner alle at det er fordi det dukker opp et kart
NiN = uforståelig kodenavn som bare gir mening for eksperter, noen synes kanskje det ser corny ut med liten i?

Hva med noe litt lengre, men mer beskrivende som for eksempel "Natur i Norge"?

**Comment by runningbones** [comment]
Enig. Vi bytter ut "Økologisk grunnkart" med "Natur i Norge".  internt kan jeg bruke NiN-kart for å unngå sammenblanding med selve NiN-systemet og NiN-delen av nettsida vår.

**Comment by amundn** [comment]
ok, da bytter jeg for tredje gang ...

**Comment by amundn** [comment]
I tillegg til klienten må det byttes i Firebase og kanskje api?

**Comment by runningbones** [comment]
Mangler også et sted i klienten: 
![image](https://user-images.githubusercontent.com/31729342/38598671-a2475988-3d5d-11e8-9164-3c7d6761791f.png)

**Comment by amundn** [comment]
Dette kommer fra firebase @runningbones

**Comment by bjornreppen** [comment]
Repo var oppdatert, men ikke ny database ikke bygd.  Fixed.

**Comment by amundn** [comment]
![image](https://user-images.githubusercontent.com/13641108/38606399-31bcf43e-3d76-11e8-8e26-aa213228eec0.png)
Ligger fortsatt som navn på toppnivå

**Comment by bjornreppen** [comment]
Ok.  Prøver igjen.
