### ISSUE TITLE
Naturområdeinfo mangler ved klikk i kart/ er veldig treg

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#285]
### Issue and Steps to Reproduce
Naturområdeinfo mangler ved klikk i kart
### Versions
20180418 kl 08.00
### Screenshots
![image](https://user-images.githubusercontent.com/31729342/38914327-3a93533c-42df-11e8-847b-23f965652dcb.png)

#### Expected
info om det kartlagte området

### Additional Details
Kommer av og til opp etter laaaaaaang tid

**Comment by amundn** [comment]
Denne kaller på artskart api'en, f.eks:
https://test.artsdatabanken.no/nin_master/Api/data/GetMetadataByNatureAreaLocalId/72F3E4DC-248A-47E4-99A9-836C26A4DD2E
https://test.artsdatabanken.no/nin_master/Api/data/GetNatureAreaByLocalId/72F3E4DC-248A-47E4-99A9-836C26A4DD2E
Har hørt det har vært litt hastighetsproblemer med artskart også de siste dagene, så kan være relatert. Ellers var det vel snakk om å gå bort fra å bruke denne api'en?

**Comment by bjornreppen** [comment]
Vise placeholdere mens data lastes #237

**Comment by jarped** [comment]
Burde ha blitt fikset av https://github.com/Artsdatabanken/grunnkart-dataflyt/issues/28
