### ISSUE TITLE
Lenke til info om "koder" i treet/venstremarg

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#290]
### Issue and Steps to Reproduce
Ønsker å lenke til info "om" koden fra navigering i treet. Eksempel: du klikker deg gjennom natursystemhierarkiet, og ønsker å lese om hva helofyttsump. I dag må du finne et objekt med koden, og klikke "i" knapp derfra for å finne mer info.
### Versions
20180420
### Screenshots
Eksempel fra punktinfo
![image](https://user-images.githubusercontent.com/31729342/39048013-51ef8ae6-449c-11e8-8833-d6579739e6ad.png)

Forslag plassering ny "i"
![image](https://user-images.githubusercontent.com/31729342/39048167-ca7046e0-449c-11e8-9abe-2655f036ddad.png)

### Additional Details
Ønske fra Mdir

**Comment by amundn** [comment]
Hvis det skal ligge en "i" med url der, må først den aktuelle urlen legges inn i firebase barnenoden slik:
![image](https://user-images.githubusercontent.com/13641108/39052518-8e06c2dc-44ac-11e8-9424-8da0bf71edf4.png)

**Comment by amundn** [comment]
*Altså ikke samme url som for foreldrenoden, men tilsvarende
