### ISSUE TITLE
Fjern fargevelger fra kodekatalog

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#295]
Statiske farger i katalog

![image](https://user-images.githubusercontent.com/281359/39195403-1024dee4-47e0-11e8-9faf-dc82b2b230b4.png)

Justerbare farger i lagoversikten:

![image](https://user-images.githubusercontent.com/281359/39195443-26154af4-47e0-11e8-8ebf-a45cb560d622.png)

**Comment by amundn** [comment]
Hvis man justerer i lagoversikten, skal det da bare brukes i lagoversikten, dvs alltid ta farger til katalog fra firebase?

**Comment by bjornreppen** [comment]
Denne ser ut til å allerede være implementert.
