### ISSUE TITLE
Unhandled Rejection (Error): Style is not done loading

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#300]
![image](https://user-images.githubusercontent.com/281359/39314332-46e923c8-4974-11e8-9acb-7725d7e7d85b.png)

Innimellom ved lasting av siden så kommer den ikke opp.

**Comment by amundn** [comment]
Si ifra om denne fortsatt dukker opp

**Comment by bjornreppen** [comment]
Fjernet i #490
