### ISSUE TITLE
Vis placeholdere så brukeren forstår at det jobbes med å skaffe informasjon

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#301]
![image](https://user-images.githubusercontent.com/281359/39316103-a6be9c0c-4978-11e8-85df-361aaa35c26a.png)

For eksempel aktuelt i vinduet som viser informasjon om punkt da det kan ta en del tid å laste.

**Comment by jarped** [comment]
Duplikat av #237?

**Comment by bjornreppen** [comment]
Ja, duplikat
