### ISSUE TITLE
Artsnode uten innhold, kan ikke gå til artssidene

### ISSUE THREAD

**Issue by amundn** [Artsdatabanken/ratatouille#309]
### Issue and Steps to Reproduce
Trykk på art: 
![image](https://user-images.githubusercontent.com/13641108/39349026-b4ba843e-49f9-11e8-917a-281b46f2fd3c.png)
Mangler innhold:
![image](https://user-images.githubusercontent.com/13641108/39349040-c2d81374-49f9-11e8-9385-63dcb83ef298.png)

Gå til url for en art:
![image](https://user-images.githubusercontent.com/13641108/39348950-74d3bc8c-49f9-11e8-9176-c84f0cb18457.png)
Havner bare tilbake på rot

**Comment by bjornreppen** [comment]
Blokkert av [kverna#87](https://github.com/Artsdatabanken/kverna/issues/87)

**Comment by bjornreppen** [comment]
... og plutselig da jeg skulle prøve igjen fant jeg den egentlige årsaken til at artene er borte.. det er en teknisk feil i [taxon/all](https://www.artsdatabanken.no/api/taxon/all) som gjør at json som kommer i retur er korrupt.. mangler komma mellom objekter.

**Comment by bjornreppen** [comment]
Løst i [kverna/87](https://github.com/Artsdatabanken/kverna/issues/87)
