### ISSUE TITLE
Naturområder med > 100% dekning

### ISSUE THREAD

**Issue by jarped** [Artsdatabanken/ratatouille#328]
### Issue and Steps to Reproduce

Antageligvis er det overlappende naturområder som er grunnen til problemet
### Screenshots
![image](https://user-images.githubusercontent.com/3570752/39573404-5a78b674-4ed3-11e8-973c-7ae2a4595301.png)

### Additional Details
Link som førte til resultatet som vist i screenshot:
https://grunnkart.firebaseapp.com/punkt/10.254264240037926,63.341558056455185

**Comment by runningbones** [comment]
Ved å kun velge høgstaudeskog ser jeg at det er et mindre polygon under det sammensatte naturområdet. Skyldes dermed at det ligger to objekter stablet oppå hverandre,

**Comment by runningbones** [comment]
Nyest først. Vurderer historikkfunksjonalitet ved behov.
