### ISSUE TITLE
For mange Verneområder vises samtidig

### ISSUE THREAD

**Issue by jarped** [Artsdatabanken/ratatouille#349]
**Describe the bug**
Når man navigerer seg til Verneområder via katalog legges det til ett lag pr verneområde. Dette blir for mange. Vi trenger å legge til ett eller flere mellomnivåer for å redusere antallet som vises samtidig.

**To Reproduce**
1. Go to https://grunnkart.firebaseapp.com/
2. Open developer tools to see console
3. Click on katalog 
4. Click on Naturverneområde 
5. Observe that one layer is added pr verneområde. This takes a while, but will eventually finish. However, the user experience will now be very laggy.

**Expected behavior**
When following point 4 we should see categories on a higher level. Some alternatives are
* Verneform
* ~~Verneplan~~
* ~~Forvaltningsnivå~~
* ~~Truetvurdering~~
* ~~IUCN~~

**Screenshots**
![image](https://user-images.githubusercontent.com/3570752/39994776-8e29acda-577a-11e8-918f-8795cfc91ace.png)

**Additional context**
Blocked by https://github.com/Artsdatabanken/kverna/issues/113

**Comment by runningbones** [comment]
Om vi skal velge en er verneform mest aktuell!

**Comment by jarped** [comment]
Ser bedre ut, men da vil vi nok få samme problemet igjen på neste nivå når brukeren velger naturreservat. Der er det 2616 områder.

Kan virke som vi må ha 2 nivåer for å havne på et akseptabelt antall lag. Ellers må vi vurdere andre tiltak.

![image](https://user-images.githubusercontent.com/3570752/39998872-b8bb6774-5787-11e8-9348-1bad5df5a810.png)

**Comment by runningbones** [comment]
Mdir distrubuerer datasettet som wms/ArcGis REST med en "aggregert" liste over verneformer: https://kartkatalog.miljodirektoratet.no/MapService/Details/vern

![image](https://user-images.githubusercontent.com/31729342/40043995-6c5ca772-5826-11e8-8a28-e563562ed473.png)

**Comment by bjornreppen** [comment]
Skal vi da gjøre det samme for kommuner og fylker? :dagger:

**Comment by jarped** [comment]
Bare hvis det er et problem med 400+ lag i visningen. Verneområdene har 2500+ og der har vi jo sett at det blir et problem

**Comment by runningbones** [comment]
Høres fornuftig ut. 

Kanskje kan vi implementere punktinfo vha wms (http://wms.miljodirektoratet.no/arcgis/services/vern/mapserver/WMSServer) på lik linje med stedsnavn?

**Comment by jarped** [comment]
Legger inn punktinfo:
https://github.com/Artsdatabanken/ratatouille/pull/355
https://github.com/Artsdatabanken/ratatouille/commit/752fa18d5cd592d1c1129d38121a4e3a4d004e37

Kan navigeres til omådet ved å klikke.

**Comment by runningbones** [comment]
Ser av e-postkorrespondanse mellom Jarle og Mdir at nye wms-tjenester støtter https lanseres primo juni.

**Comment by jarped** [comment]
Lukker denne siden verneområdene nå har et akseptabelt  antall

**Comment by runningbones** [comment]
Ny wms lansert: https://kartkatalog.miljodirektoratet.no/MapService/Details/vern
