### ISSUE TITLE
NA I - problemer med vining i alle zoomnivå

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#350]
**Describe the bug**
NA I - problemer med visning av tilset i alle zoomnivå

**To Reproduce**
1. Go to: https://grunnkart.firebaseapp.com/katalog/na/i 
2.  panorer kartet til de sørlige delene av Jostedalsbreen
3. zoom ut og inn

**Expected behavior**
å se isbreene i alle zoomnivå

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/39995561-e0649c24-577c-11e8-800c-1fdb4b5f50f3.png)
![image](https://user-images.githubusercontent.com/31729342/39995569-ebad7862-577c-11e8-9909-db13c41c4cff.png)
![image](https://user-images.githubusercontent.com/31729342/39995586-fb5f4dbc-577c-11e8-8975-f702903c5a49.png)

**Comment by jarped** [comment]
Klarer ikke reprodusere. Kan ha vært en hickup fra da tileserver ble reinstallert tidligere i dag. Stenger issuen for nå.
