### ISSUE TITLE
verneområder - treghet i visning/presentasjon

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#351]
**Describe the bug**
svært treg visning av verneområder

**To Reproduce**
1. Go to https://grunnkart.firebaseapp.com/katalog/vv 

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/39995736-79def5ca-577d-11e8-8674-14f82b375210.png)

**Comment by jarped** [comment]
Duplicate of https://github.com/Artsdatabanken/ratatouille/issues/349
