### ISSUE TITLE
Fylke/Kommune i katalog viser også verneområder

### ISSUE THREAD

**Issue by jarped** [Artsdatabanken/ratatouille#353]
**Describe the bug**
Visning av fylke/kommune i Katalog viser også verneområder

**To Reproduce**
1. Go to https://grunnkart.firebaseapp.com/katalog/ao
2. Click on Oppland
3. Scroll down to 15 Vågå
4. Både kommunepolygon og verneområder vises samtidig

**Expected behavior**
Bare kommunepolygon vises

**Screenshots**
![image](https://user-images.githubusercontent.com/3570752/40050651-58a162f6-5838-11e8-811e-cd601030951a.png)

**Additional context**
Vi må skille på når en kode er brukt som en primærnøkkel eller fremmednøkkel. Opprette et separat prefix som betyr fremmednøkkel: FK_AO_05-15 for objekter som ligger i, men ikke er, Vågå.

Evt. kan man angi hoved-prefix som et egen attributt og sjekke om en gitt tag skiller seg fra denne, men dette virker litt tungvint.

**Comment by bjornreppen** [comment]
Fikset i [kverna/#114](https://github.com/Artsdatabanken/kverna/issues/114)
