### ISSUE TITLE
URL og skjermbilde viser forskjellige ting

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#358]
**Describe the bug**
![image](https://user-images.githubusercontent.com/281359/40171732-6f85aeec-59cc-11e8-87a8-9c0f8a0f494e.png)

**To Reproduce**
1. Go to https://grunnkart.firebaseapp.com/katalog/vv

URLen endrer seg automatisk til /katalog
men skjermbilde viser Naturvernområde

**Comment by amundn** [comment]
fikset av https://github.com/Artsdatabanken/ratatouille/pull/359
