### ISSUE TITLE
Valgte lag - forslag til struktur/funksjonalitet 

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#360]
**Is your feature request related to a problem? Please describe.**
Valgte koder/valgte lag popper i dag opp i en egen boks. Denne "henger" pt ikke helt sammen med resten av gui.  Dersom bruker ønsker å "slå av" et valgt lag må dette "slettes", for deretter å legges til på nytt.

**Describe the solution you'd like**
Brukere vil kunne ha behov for å slå av og på visning av sine valgte lag (samt endre transparency/farge), i tillegg til å se dagens liste over hvilke lag som er synlig i kartet.

På http://www.emodnet.eu/geoviewer/#!/ har de en løsning for katalog av alle kartlag, med en egen "tab" for de lagene brukeren selv har valgt. På tab for valgte lag kan brukeren skru av/på visning uten at laget fjernes fra lista, samt endre etyling (kun transparency). 
![image](https://user-images.githubusercontent.com/31729342/40229367-509429f0-5a94-11e8-8849-6b4523fd8fa0.png)
 En lignende løsning kan være aktuell for oss (usikker på om det skal være en "tab", åpen for synspunkter!)

**Comment by amundn** [comment]
Ser at her vises kun de valgte lagene, ingen ting fra katalogen vises før det er valgt, 
Bjørn er glad i tabs har jeg hørt :)

**Comment by bjornreppen** [comment]
:+1 Jeg synes dette ser bra ut funksjonelt (visuelt ser det forferdelig ut :-))

Tabbene er ikke nødvendig. "Add layer"-knappen gjør jobben like bra (1 klikk).  Synes ikke konsept med tabber her passer særlig godt, da de inneholder helt forskjellige konsepter.. se for deg en tab med handlekurv og en annen med butikkhylle.  Dersom tabbene het Natursystem og Landskapstyper synes jeg taber kunne fungert bedre (kategorier av samme "greie")

**Comment by amundn** [comment]
Vi viser noden vi står på (aktivt lag) samt barna (et lag pr barn) og i tillegg et eget lag for det vi ev. hovrer over (opplyst lag). Tenker du vise alt dette pluss alle valgte lag?

**Comment by amundn** [comment]
![image](https://user-images.githubusercontent.com/13641108/40362443-dc8f71cc-5dcc-11e8-94dc-aec54f644391.png)

?

**Comment by runningbones** [comment]
Synes både og utseende og funksjonalitet på "av/på" switch er topp, men er for meg virker det som om dagens "av" bør være "på" og motsatt. Synspunkter?

![image](https://user-images.githubusercontent.com/31729342/40482444-1ce9d026-5f55-11e8-8295-83a1383ddaf7.png)

![image](https://user-images.githubusercontent.com/31729342/40482468-35bcb442-5f55-11e8-9cbb-01276966f626.png)

**Comment by runningbones** [comment]
Savner funkjsonalitet for å "fjerne" aktive kartlag.

**Comment by bjornreppen** [comment]
Snarvei: Ctrl+W

**Comment by amundn** [comment]
Fjerning kan gjøres fra dette skjermbildet
![image](https://user-images.githubusercontent.com/13641108/41094924-36bdc4ac-6a50-11e8-926c-6f10bcc11886.png)
