### ISSUE TITLE
Valgte lag: visning av children

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#361]
**Is your feature request related to a problem? Please describe.**
Når vi i dag navigerer til f.eks. natursystem i treet, og trykker  + tegnes det valgte laget et hierarkisk nivå høyere enn der hvor brukeren er/det bruker ser i klienten. 

**Describe the solution you'd like**
Ved å velge + i treet skal alle children legges til i "valgte lag".  se issue #360 

Eks. velger brukeren Natursystem i treet, og klikker + 
![image](https://user-images.githubusercontent.com/31729342/40229810-ab0c64d2-5a95-11e8-8c78-04f707a8c489.png)

Bør alle hovedtypegrupper legges til som valgte lag (med tegneregler tilsvarende det brukeren så da hen klikket +.

**Comment by amundn** [comment]
Hvis vi legger til node med alle barn, tror jeg at jeg vil foretrekke at man ikke kan slette enkelt-barn fra lista etterpå (dvs man kan slette hele noden med barn eller skru visning på/av for enkelte barn)

**Comment by runningbones** [comment]
Foreslår at vi viderefører den implementerte endringen mht til tegning av barn når et kartlag gjøres aktivt. Ønsker en foranring i  GUI av "aktive kartlag venstremeny":

Parent (koden som legges til) er den som vises under aktive lag, men man kan velge å se alle childeren ved å ekspandere listeelementet (likt som for natursystem) ved punktinfo: 
![image](https://user-images.githubusercontent.com/31729342/40916574-87c08fd0-6800-11e8-9c31-e244a76e49a0.png)

Mockup: 
![image](https://user-images.githubusercontent.com/31729342/40916743-27cafe70-6801-11e8-85bc-c34f6a4e9e86.png)

**Comment by amundn** [comment]
Delvis adressert i https://github.com/Artsdatabanken/ratatouille/pull/445

**Comment by runningbones** [comment]
er det mulig å få expand/collaps plassert der hvor fargekode til parent i dag vises? Denne fargekoden er ikke mulig å gjenfinne i kartet (men  kun på et høyere nivå i katalogen)

**Comment by amundn** [comment]
Du ser fargen i kart om du skrur av visning på barna:
![image](https://user-images.githubusercontent.com/13641108/41100675-47261b7a-6a62-11e8-9bd3-e45dd9c70a96.png)

**Comment by amundn** [comment]
Lukker denne, lag heller eventuelt en ny task for flytting av ^-symbol
