### ISSUE TITLE
Hover fungerer ikke på Natursystemnivå

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#362]
* Naviger til Natursystem https://grunnkart.firebaseapp.com/katalog/na
* Dra musa over polygoner - ingenting skjer?
![peek 2018-05-18 12-33](https://user-images.githubusercontent.com/281359/40230445-c9596d3e-5a97-11e8-9eea-8a170c4b3c44.gif)

**Comment by amundn** [comment]
Mulig hover-laget har havnet under det valgte eller aktive laget

**Comment by bjornreppen** [comment]
![hover](https://user-images.githubusercontent.com/281359/40361436-9f55474e-5dc9-11e8-9ea5-a3b16ad35bd7.gif)

Fungerer ikke hos meg?

**Comment by bjornreppen** [comment]
Fungerer på enkelte av områdene. Ikke snø og is hos meg.

**Comment by amundn** [comment]
Problemet er at snø og is ikke har lokal-id. @jarped kan fikse

**Comment by bjornreppen** [comment]
Ja, men kanskje bedre å fjerne lokalid og gjøre hele jobben på serversiden.
Løser utfordrring med at:
 - Lasting fra URL ikke finner lokalid fordi kartet ikke er ferdig lasta
 - Varierende innhold i tiles avhengig av zoom nivå
 - Man potensielt laster masse data som ikke blir presentert (bare brukt til hit testing)

**Comment by bjornreppen** [comment]
Og.. det burde ikke være nødvendig å ha lokalId for å avgjøre at dette er snø og is?  Det bør vel holde med koden NA_I?

**Comment by jarped** [comment]
Vi bruker lokalid som nøkkel for å slå opp i metadata

**Comment by amundn** [comment]
Hover går på et enkelt område, ikke på koden, derfor lokal-id

**Comment by bjornreppen** [comment]
Ikke sett så nøye på det før, men tenker at det hadde vært realt om hover på kartet fungerer likedan som hover i katalogen.. dvs. at alle NA_I lyser opp når du plasserer musa over et område som er NA_I.

**Comment by amundn** [comment]
Årsaken til å markere et enkelt område har jo også med at dersom du klikker der får du info om området du klikket på, ikke om typen. Hvis alt i samme typen lyser opp på hover ville jeg forventet info om typen og ikke området.

**Comment by jarped** [comment]
Fixes av https://github.com/Artsdatabanken/grunnkart-dataflyt/commit/ca244b59d09269dc8e3125fb683fcb78b4526e19 ved å generere lokalid ved import.

Vi kan se nærmere på dette etter vi har laget noe på serversiden. Hover trenger å ha noe unikt hvis vi ønsker å se enkeltområder, men dette behøver ikke være lokalid.
