### ISSUE TITLE
Lugger veldig ved skrolling i katalogen

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#365]
**Describe the bug**
Scrolling opp og ned spesielt når det er en del elementer går i sneglefart.  Det kan virke som at hele kodevinduet blir rendret på nytt for hver frame (pga. hover events?).
**To Reproduce**
1. Gå til verneområder i Trøndelag
2. Scroll opp og ned
3. Alt henger

**Expected behavior**
Umiddelbar respons.

**Comment by amundn** [comment]
Ser ut til å fungere fint her nå, er det fortsatt et problem?

**Comment by bjornreppen** [comment]
Snurrer bedre, men områdene lyser ikke opp?
