### ISSUE TITLE
Geometrier vises ikke når klienten åpnes på natursystem

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#366]
Ved ren oppstart fra https://grunnkart.firebaseapp.com/katalog/na  vises ikke natursystemene. Det samme gjelder etter en refresh av siden.

![nada](https://user-images.githubusercontent.com/281359/40361310-29814662-5dc9-11e8-9fee-422aaf8cdbc3.gif)

**Comment by amundn** [comment]
Problemet har å gjøre med at Mapbox ikke er ferdig med å laste stilen når koden som skal legge til det aktive laget blir kjørt, så da blir det ikke lagt til. Dette skjer her: 
https://github.com/Artsdatabanken/ratatouille/blob/master/src/Kart/Mapbox/index.js#L110
