### ISSUE TITLE
Katalog/visning av geometri ved hover i katalog

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#368]
**Is your feature request related to a problem? Please describe.**
I dag vises all geometri tilhørende katalogelementet ved hovring i allerede ved "rotpunkt" i katalogene

![image](https://user-images.githubusercontent.com/31729342/40412512-cff1ef88-5e73-11e8-9455-0330d4aad01e.png)

**Describe the solution you'd like**
Foreslår at man nå må gjøre et klikk inn på f.eks. AO før geometri vises.

**Comment by amundn** [comment]
En måte å gjøre dette på er vel å la vær å tagge områdene med toppnivå-koden (NA, AO etc) dette er vel årsaken til at ingen ting vises på rot-nivået nå

**Comment by bjornreppen** [comment]
Løst i datagrunnlaget ved å fjerne toppnivåkoder fra vector tiles.
