### ISSUE TITLE
Hover fungerer bare på NA

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#369]
Det kan se ut som hover i kartet bare fungerer på geometri som hører under natursystem?

![barena](https://user-images.githubusercontent.com/281359/40414077-a73c08c2-5e77-11e8-989a-765724827159.gif)

Bør fungere uavhengig av grein i katalogen.

**Comment by amundn** [comment]
Har fortsatt med lokalId å gjøre :) Hover setter filter basert på lokalId

**Comment by amundn** [comment]
Relatert til #362
