### ISSUE TITLE
Natursystem - geometri vises kun for NA I

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#372]
**Describe the bug**
Natursystem - geometri vises kun for NA I
**To Reproduce**

https://grunnkart.firebaseapp.com/katalog/na

**Expected behavior**
se alle natursystem i basen
**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/40467206-34530858-5f29-11e8-8143-baef74dc6c04.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome

**Comment by runningbones** [comment]
"Countbar" fungerer for alle hovedtypegrupper, men ikke NA I (som har geometri...)

**Comment by jarped** [comment]
Driver og kjører ny eksport. Natursystemene skal være på plass igjen. Ang countbar er det pga bruk av forskjellige databaser i dataeksport og API.

**Comment by jarped** [comment]
Alle NA er nå tilbake

**Comment by runningbones** [comment]
Fortsatt ikke visning av NA I under "punktinformasjon"
