### ISSUE TITLE
Bakgrunnskartmeny - vanskelig å finne

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#375]
**Describe the bug**
Etter at søkevinduet ble flyttet til katalogen, er det tildels svært vanskelig å finne bakgrunnskartmenyen. Når du først har funnet den, blir er det krevende å finne katalogen.

**To Reproduce**
1. Go to https://grunnkart.firebaseapp.com/
2. Click on venstrepil i søkevindu inntil du kommer til hamburgermeny
3. bytt bakgrunnkart
4. prøv å finn tilbake til katalogen......

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/40483187-65dc002c-5f57-11e8-9eba-730cf7f0a478.png)

**

**Comment by amundn** [comment]
Mulig det har blitt fikset her nå, synes ikke det er vanskelig, men kan hende jeg er noe inhabil. Kan du se om det fortsatt er et problem?
