### ISSUE TITLE
"Vis i kart" feiler

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#397]
**Describe the bug**
mapbox-gl.js:551 Map cannot fit within canvas with the given bounds, padding, and/or offset.

**To Reproduce**
1. Go to NA_I
2. Click on Vis i kart

**Comment by amundn** [comment]
"Vis i kart"-knappen er fjernet?

**Comment by bjornreppen** [comment]
Mistenker at @amundn kanskje har laget en responsiv design her så den ikke vises med mindre du har et vindu som ikke er så stort? ;-)

**Comment by bjornreppen** [comment]
Gruppert koordinatene igjen slik mapbox ville ha dem
