### ISSUE TITLE
AppBar: Vise tittel på skjermbilde

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#406]
![image](https://user-images.githubusercontent.com/281359/40643515-b1822822-6320-11e8-8941-1445f2dfb04a.png)

Når man er inne i menyer, vis tittelen på den aktive menyen istedet for søketekstboksen.

**Comment by amundn** [comment]
Så i eksemplet her skal det stå Terreng der det nå står "Natur i Norge"? Har jeg forstått det rett?

**Comment by runningbones** [comment]
nesten i boks. Noe småfix

**Comment by bjornreppen** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/281359/49648988-13a4bf80-fa28-11e8-9f14-71bdb6423d3a.png)
