### ISSUE TITLE
Integrer rasterlag

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#408]
Integrer rasterene fra [dataflyt/202](https://github.com/Artsdatabanken/ratatouille/issues/202#issuecomment-392751803)

**Comment by jarped** [comment]
![image](https://user-images.githubusercontent.com/3570752/40707896-46a089c2-63f2-11e8-9bce-22582bb64899.png)

Her er en 8-bits png via tileserver med 0 som nulldata (må skrelles bort et sted). men hvordan skal vi komme oss dit i katalogen? Har vi en kode for rådata for seksjoner/soner?

**Comment by runningbones** [comment]
Mangler kode for flyttall (har kun for klassedelte):
https://artsdatabanken.no/api/Graph/NiN2.0/6so 
https://artsdatabanken.no/api/Graph/NiN2.0/6se

**Comment by bjornreppen** [comment]
2 ting som kan være kjekt her:

* 256x1 pixel .png LUT (look up table) til mapping fra gråtone til klassens fargekode
* JSON med subkoder som nøkkel og start/sluttverdi (før normalisering), eks:
```json
klasse: {
  "1": {"område": [-4.1, -3.2], "farge": "#f0f"},
  "2": {"område": [-3.2, -1.3], "farge": "#ff0"},
  "3": {"område": [-1.3, 1.9], "farge": "#44f"},
}
```

**Comment by bjornreppen** [comment]
Kan vi i første omgang bare avlede klassene fra datasettet?

**Comment by bjornreppen** [comment]
@runningbones sjekker om han finner en tabell hvis han blir ferdig med alle møtene..

**Comment by jarped** [comment]
Tror det første vi må finne ut av er nettopp hvordan vi mapper om fargene fra gråtone til de som er definert i farge-tabellen:
https://github.com/mapbox/mapbox-gl-js/issues/3889

**Comment by bjornreppen** [comment]
@jarped mapping har vi klart:

"256x1 pixel .png LUT (look up table) til mapping fra gråtone til klassens fargekode"

GLSL:
`vec4 farge = texture2D( textureLUT, vec2(gråtoneVerdi, 0.5);`

**Comment by runningbones** [comment]
Avvent LA-raster.
