### ISSUE TITLE
Bioklimatise soner - mulig å legge til samme sone 2 ganger

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#424]
**Describe the bug*
Fikk lagt til BS-6SO-1 to ganger, og disse lagene konkurrerer som aktive kartlag.

**To Reproduce**
1. legg til BS-6SO-1
2. legg til BS-6SO'
3. velg aktive kartlag
4. toggelbar er motsatt på de to like kodene...

**Expected behavior**
ikke mulig å legg til to ganger

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/40839465-02b0ce22-65a3-11e8-8da4-497202b8c3ba.png)

**Comment by amundn** [comment]
Den ene er kommet inn som et barn, den andre er lagt til som koden selv. Dersom barnet hadde hatt flere barn får vi ikke lagt til dem dersom det sperres for å legge til koder som allerede er inne som barn.

**Comment by amundn** [comment]
*Dette er generelt og ikke spesifikt for bioklimatiske soner
