### ISSUE TITLE
Mobil - umulig å vise katalog

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#434]
**Describe the bug**
Ikke mulig å vise katalog på mobil (IOS)
**To Reproduce**

1. Go to grunnkart.firebase.com
2. Click on katalog

**Expected behavior**
Katalogen åpener seg...

**Comment by jarped** [comment]
Åpner for sikkerhets skyld. Må verifisere at det faktisk virker på mobil.

**Comment by jarped** [comment]
Fixed, men nå trenger vi en måte å stenge venstremenyen på så vi kan se kartet #474
