### ISSUE TITLE
"zoom to layer" - aktive kartlag

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#438]
**Is your feature request related to a problem? Please describe.**
Kan være vanskelig å finne igjen sjeldne/små forekomster i kartet. 
f.eks. https://grunnkart.firebaseapp.com/lag/VV_3 

**Describe the solution you'd like**
En "zoom to layer" funksjon, hvor man bruker den minste bbox hvor det man har valgt er innfor som vinsing i kartflata. Bør være mulig per aktive lag.

**Comment by amundn** [comment]
Vi har denne funksjonaliteten (men den fungerer ikke for tiden, se https://github.com/Artsdatabanken/ratatouille/issues/397 )
