### ISSUE TITLE
Visning av localID

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#447]
**Is your feature request related to a problem? Please describe.**
Mdir ønsker at sin localID (naturområdeID fra egen SDE) vises ned klikk i kart på et naturområde. 

**Describe the solution you'd like**
Foreslår at vi henter inn naturområdeID fra en wms (som for bioklima)

**Describe alternatives you've considered**
Foreslår at vi unngår å legge dette på i tileset, blir mange tegn (Tileset blir større/tregere?)

**Comment by jarped** [comment]
Fixed by https://github.com/Artsdatabanken/ratatouille/pull/458
