### ISSUE TITLE
"Zoom til" - også for aktive lag

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#603]
**Is your feature request related to a problem? Please describe.**
Kan i dag benytte "zoom til" kode (inkl. barn/barnebarn...)  fra katalogen. Når et kartlag er gjort aktivt, må bruker tilbake til "info" og deretter benytte "zoom til" i katalogen 

**Describe the solution you'd like**
Legg til samme funksjonalitet under "aktive kartlag". Foreslår i første omgan å legge funksjonaliteten på samme sted som man endrer farge/etiketter/fjerner kode fra aktve kartlag:

![image](https://user-images.githubusercontent.com/31729342/44899177-58baa680-ad01-11e8-817c-f46e44ff9de1.png)

**Comment by runningbones** [comment]
Kan også legge nederst sammen men fjern/info

**Comment by bjornreppen** [comment]
![zoom](https://user-images.githubusercontent.com/281359/46380351-34583e00-c6a2-11e8-8239-74510967249d.gif)

**Comment by bjornreppen** [comment]
Denne har vi løst i #654
