### ISSUE TITLE
Mangler metadata for  naturområder.

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#609]
For eksempel sier APIet for https://vector.artsdatabanken.no/ogapi/codes/13.13054371160307/65.43752360313434
at det skal finnes et naturområde med id ebcf2f96-afce-483c-abb1-3c306797a507

Dette området finnes ikke på https://test.artsdatabanken.no/data/json/ninMetadata/EBCF2F96-AFCE-483C-ABB1-3C306797A507.json

**Comment by runningbones** [comment]
@jarped sjekker saken

**Comment by runningbones** [comment]
Fint om @bjornreppen ser på en quickfix.

**Comment by bjornreppen** [comment]
Dette gjelder NA-I - snø- og issystemer som ikke kommer fra NiN-kartlegging.  De får en generert id ved import, men vi har ingen metadatafil.

Forslag fra @jarped om at vi fjerner iden på dem i databasen inntil et evt. behov oppstår.

**Comment by runningbones** [comment]
Kan se ut som om denne fortsatt er aktuell:
![image](https://user-images.githubusercontent.com/31729342/51179113-f08deb00-18c4-11e9-951b-5c5ea7094b4f.png)
