### ISSUE TITLE
Feil med bioklimatiske soner/seksjoner

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#611]
Soner mangler, seksjoner gir flere svar på 1 punkt.

Se https://vector.artsdatabanken.no/ogapi/codes/7.931516626397422/61.51666518426392
```json
{
"BS_6SE-2": {
"key": "Bioklimatiske seksjoner",
"value": "Klart oseanisk seksjon (o2)",
"ids": [
"032f9a00-be8f-4d33-afe6-b742965a42ce",
"3331"
]
},
"BS_6SE-3": {
"key": "Bioklimatiske seksjoner",
"value": "Svakt oseanisk seksjon (o1)",
"ids": [
"032f9a00-be8f-4d33-afe6-b742965a42ce"
]
}}
```

**Comment by runningbones** [comment]
leveres i API, vises kun soner ved "klikk i kart"

**Comment by bjornreppen** [comment]
Fungerer nå?
![image](https://user-images.githubusercontent.com/281359/46380250-ec391b80-c6a1-11e8-91f6-2fa3e1c1c593.png)
