### ISSUE TITLE
Natursystem - mange polygon mangler i visning

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#904]
**Describe the bug**
Mange polygoner er ikke synlig i innsynet

**To Reproduce**
1. Go to https://nin.artsdatabanken.no/katalog/NA
2. klikk 'aktiver'
3. zoom til et område med kartlagte natursystem (f.eks "ringen" i Grimsdalen)

**Expected behavior**
At alle NA i basen vises på dette nivået

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/49497851-b105c500-f869-11e8-87fb-72bce5a21aba.png)

![image](https://user-images.githubusercontent.com/31729342/49497908-cbd83980-f869-11e8-8196-931f098effce.png)

**Additional context**
finner info om de manglende polygonene ved klikk i kart. blir synlige når den aktuelle typekoden aktiveres.

**Comment by jarped** [comment]
Fixed by https://github.com/Artsdatabanken/ratatouille/pull/906
![image](https://user-images.githubusercontent.com/3570752/49511409-6006c880-f88b-11e8-86a9-1c57c43270c7.png)
