### ISSUE TITLE
LKM mangler i katalaog

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#905]
**Describe the bug**
Miljøvariabler/LKM (eks. KA og S3) mangler i 'https://nin.artsdatabanken.no' 

Ligger på https://maps.artsdatabanken.no/NA/LKM/

**Comment by bjornreppen** [comment]
Fixed: 

https://nin.artsdatabanken.no/katalog/NA-LKM

![image](https://user-images.githubusercontent.com/281359/49645032-b6564180-fa1a-11e8-8faa-352c807142e9.png)
