### ISSUE TITLE
LKM - S3E og S3F: Hierarki/løvnodeutfordringer 

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#936]
Bakgrunn:
LKM S3 er den eneste flerdimensjonale LKM, det vil si en "overordnet" LKM sammensatt av flere underordnede LKM'er.  se https://www.artsdatabanken.no/Pages/179770 

Utfrodring:
VIser i dag løvnodene (basistrinn) i ven stremeny, men ikke mulig å velge løvnode (for visning)

Løsningsforslag:
Ønsker å se data på basistrinnivå (løvnode)

**Comment by bjornreppen** [comment]
Kanskje vi kunne vurdere å sette en egenskap på typen som fortalte hva slags type innhold den har?

**Comment by runningbones** [comment]
@bjornreppen God ide!
