### ISSUE TITLE
klikk i kart - S3

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#937]
**Is your feature request related to a problem? Please describe.**
S3-vertdier ligger vises ikke ved klikk ikart, men er en del av vectorAPI. Se f.eks. https://vector.artsdatabanken.no/ogapi/codes/12.682876590605053/68.8113136440978 

**Describe the solution you'd like**
se S3E e og s3F ved klikk i kart på samme måte som kalk.

#936

**Comment by jarped** [comment]
Fikset, men VectorQuery må startes på nytt etter import/eksport pga lasting av geometri-id'er i minnet.
