### ISSUE TITLE
Umulig å nå "katalog" fra framsida på nin-kart

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ratatouille#984]
**Describe the bug**
Umulig å nå "katalog" fra framsida på nin-kart

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/'
2. prøv å finn katalogen

**Expected behavior**
Noe som tar meg til:
https://nin.artsdatabanken.no/Katalog

**Comment by bjornreppen** [comment]
Ja, hm.. APIet svarer ikke, hm.

https://ogapi.artsdatabanken.no/

**Comment by bjornreppen** [comment]
Skyldes #985.

**Comment by bjornreppen** [comment]
Korrupt full-tekst-indeks-fil..  justerer lesing av fil så den fortsatt starter, men uten den aktuelle søkestrengen
